---
## 1. Introduction & Context

### What is Pandas?

**Pandas** (Panel Data / Python Data Analysis Library) is an open-source library built on top of NumPy that provides **high-performance, easy-to-use data structures and data analysis tools** for Python.

Created by Wes McKinney in 2008 while at AQR Capital Management, Pandas was born out of the need to have a flexible, expressive tool for financial data analysis — something between a spreadsheet (Excel) and a database (SQL), but with the full power of Python.

At its core, Pandas gives you:
- **DataFrame**: a 2D labeled table (like a spreadsheet or SQL table)
- **Series**: a 1D labeled array (like a single column)
- Rich tools for reading/writing dozens of file formats
- Powerful indexing, merging, grouping, reshaping, and time-series operations

---

In [1]:
1+1

2

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

In [4]:
import requests 

url = 'https://raw.githubusercontent.com/fivethirtyeight/data/master/nba-elo/nbaallelo.csv'

response = requests.get(url)

# print(response.content)

In [6]:
with open("nbaallelo.csv", "wb") as f:
    f.write(response.content)

In [12]:
df = pd.read_csv("C:\\dev02\\TechM\\python\\datasets\\nbaallelo.csv")

df.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN

In [13]:
df2 = pd.read_csv("./datasets/Iris.csv")

df2.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
type(df2)

pandas.core.frame.DataFrame

#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [ ]:
import pandas as pd

In [ ]:
# two DS in Pandas -> Series and DataFrame

# Series -> 1D -> think of it like a column -> it is homogenous
# DF -> 2D -> it's like spreadsheet -> Table
#

![](./assets/series_df.png)

### Series

A Series is a one-dimensional labeled array capable of holding any data type. It is similar to a column in a spreadsheet or a single variable in statistics.

In [17]:
data = [12,24,35,48,59]
s1 = pd.Series(data)
s1

0    12
1    24
2    35
3    48
4    59
dtype: int64

In [16]:
type(s1)

pandas.core.series.Series

In [19]:
# Creating a Series from a list
# think of series as a list with index

ages = pd.Series([25, 30, 25, 40],
                  index= ['Rajesh', 'Sai', 'Nik', 'vijay'])
ages

Rajesh    25
Sai       30
Nik       25
vijay     40
dtype: int64

#### Labels
If nothing else is specified, the values are labeled with their index number. First value has index 0, second value has index 1 etc.

This label can be used to access a specified value.

In [20]:
ages["Sai"]

np.int64(30)

In [22]:
print(ages.mean())

30.0

In [23]:
print(ages.describe())

count     4.000000
mean     30.000000
std       7.071068
min      25.000000
25%      25.000000
50%      27.500000
75%      32.500000
max      40.000000
dtype: float64

In [26]:
df2.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

### DataFrame

A DataFrame is a 2-dimensional labeled data structure with columns that can be of different types. It's similar to a spreadsheet, SQL table, or a dictionary of Series objects.

#### Creating a DataFrame from a dictionary:

In [27]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Boston', 'Chicago', 'Seattle', 'San Francisco'],
    'Salary': [65000, 72000, 59000, 82000, 75000]
}

df3 = pd.DataFrame(data)

df3

      Name  Age           City  Salary
0    Alice   24       New York   65000
1      Bob   27         Boston   72000
2  Charlie   22        Chicago   59000
3    David   32        Seattle   82000
4      Eva   29  San Francisco   75000

In [ ]:
# TASK: iloc and loc

In [28]:
## Create a Data frame From a List of Dictionaries

employees = [
    {'Name': 'Alice', 'Department': 'HR', 'Hire Date': '2020-05-15'},
    {'Name': 'Bob', 'Department': 'Engineering', 'Hire Date': '2019-11-20'},
    {'Name': 'Charlie', 'Department': 'Marketing', 'Hire Date': '2021-02-10'}
]

df = pd.DataFrame(employees)
df

      Name   Department   Hire Date
0    Alice           HR  2020-05-15
1      Bob  Engineering  2019-11-20
2  Charlie    Marketing  2021-02-10

In [32]:
df2.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [33]:
df2.tail(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [38]:
df2.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [39]:
df2.shape

(150, 6)

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [41]:
a = 90.8
type(a)

float

In [ ]:
import pandas as pd

df = pd.read_csv("datasets/nbaallelo.csv")